<?php
/**
 * ProductMediaGalleryTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  GeminiCommerce\Product
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Product Service
 *
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace GeminiCommerce\Product\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ProductMediaGalleryTest Class Doc Comment
 *
 * @category    Class
 * @description ProductMediaGallery
 * @package     GeminiCommerce\Product
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ProductMediaGalleryTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ProductMediaGallery"
     */
    public function testProductMediaGallery()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "entries"
     */
    public function testPropertyEntries()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
