<?php
/**
 * ProductApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  GeminiCommerce\Product
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Product Service
 *
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace GeminiCommerce\Product\Test\Api;

use \GeminiCommerce\Product\Configuration;
use \GeminiCommerce\Product\ApiException;
use \GeminiCommerce\Product\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ProductApiTest Class Doc Comment
 *
 * @category Class
 * @package  GeminiCommerce\Product
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProductApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for productAddMediaGalleryEntry
     *
     * .
     *
     */
    public function testProductAddMediaGalleryEntry()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productBulkAddAssetsEntries
     *
     * Assets endpoints.
     *
     */
    public function testProductBulkAddAssetsEntries()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productBulkCreateAttribute
     *
     * .
     *
     */
    public function testProductBulkCreateAttribute()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productBulkDeleteProducts
     *
     * .
     *
     */
    public function testProductBulkDeleteProducts()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productBulkRemoveAssetsEntries
     *
     * .
     *
     */
    public function testProductBulkRemoveAssetsEntries()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productBulkUpdate
     *
     * .
     *
     */
    public function testProductBulkUpdate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productBulkUpdateAssetsEntries
     *
     * .
     *
     */
    public function testProductBulkUpdateAssetsEntries()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productBulkUpdateV2
     *
     * .
     *
     */
    public function testProductBulkUpdateV2()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productCreateAttributeGroup
     *
     * .
     *
     */
    public function testProductCreateAttributeGroup()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productCreateAttributeOptions
     *
     * .
     *
     */
    public function testProductCreateAttributeOptions()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productCreateEntity
     *
     * .
     *
     */
    public function testProductCreateEntity()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productCreateOptionsList
     *
     * .
     *
     */
    public function testProductCreateOptionsList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productCreateProduct
     *
     * .
     *
     */
    public function testProductCreateProduct()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productCreateProductV2
     *
     * .
     *
     */
    public function testProductCreateProductV2()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productDelete
     *
     * .
     *
     */
    public function testProductDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productDeleteAttribute
     *
     * .
     *
     */
    public function testProductDeleteAttribute()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productDeleteProduct
     *
     * .
     *
     */
    public function testProductDeleteProduct()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productGetAttributeGroup
     *
     * .
     *
     */
    public function testProductGetAttributeGroup()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productGetAttributeOption
     *
     * .
     *
     */
    public function testProductGetAttributeOption()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productGetAttributeOptions
     *
     * .
     *
     */
    public function testProductGetAttributeOptions()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productGetEntity
     *
     * .
     *
     */
    public function testProductGetEntity()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productGetOptionsList
     *
     * .
     *
     */
    public function testProductGetOptionsList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productGetProduct
     *
     * .
     *
     */
    public function testProductGetProduct()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productGetProductByCode
     *
     * .
     *
     */
    public function testProductGetProductByCode()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productGetProductByUrlKey
     *
     * .
     *
     */
    public function testProductGetProductByUrlKey()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productListAttributeGroups
     *
     * Attribute Groups endpoints.
     *
     */
    public function testProductListAttributeGroups()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productListAttributeOptions
     *
     * .
     *
     */
    public function testProductListAttributeOptions()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productListEntities
     *
     * .
     *
     */
    public function testProductListEntities()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productListOptionsLists
     *
     * .
     *
     */
    public function testProductListOptionsLists()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productListProducts
     *
     * .
     *
     */
    public function testProductListProducts()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productListProductsByIds
     *
     * .
     *
     */
    public function testProductListProductsByIds()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productListProductsBySku
     *
     * .
     *
     */
    public function testProductListProductsBySku()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productListVariantsBySku
     *
     * .
     *
     */
    public function testProductListVariantsBySku()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productRemoveMediaGalleryEntry
     *
     * .
     *
     */
    public function testProductRemoveMediaGalleryEntry()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productUpdateAttribute
     *
     * .
     *
     */
    public function testProductUpdateAttribute()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productUpdateAttributeGroup
     *
     * .
     *
     */
    public function testProductUpdateAttributeGroup()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productUpdateAttributeOptions
     *
     * rpc GetAttributeOptionByCode (product.entitymanager.GetAttributeOptionByCodeRequest) returns (product.entitymanager.GetAttributeOptionByCodeResponse) {}.
     *
     */
    public function testProductUpdateAttributeOptions()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productUpdateMediaGalleryEntry
     *
     * .
     *
     */
    public function testProductUpdateMediaGalleryEntry()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productUpdateOptionsList
     *
     * .
     *
     */
    public function testProductUpdateOptionsList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productUpdateProduct
     *
     * .
     *
     */
    public function testProductUpdateProduct()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productUpdateProductV2
     *
     * .
     *
     */
    public function testProductUpdateProductV2()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
